language: java
jdk:
  - oraclejdk8

env:
  global:
    - DEPLOY_JDK=oraclejdk8
    - DEPLOY_REPO=nbbrd/netbeans8-over-jdk11
    - DEPLOY_BIN=target/*-bin.*

deploy:
  # Github releases from tags
  - provider: releases
    api_key: "${GITHUB_KEY}"
    skip_cleanup: true
    file_glob: true
    file: "${DEPLOY_BIN}"
    on:
      tags: true
      repo: "${DEPLOY_REPO}"
      condition: $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_JDK_VERSION == $DEPLOY_JDK

cache:
  directories:
    - $HOME/.m2
